# Use the official PostgreSQL 16 image
FROM postgres:16-alpine

# Expose PostgreSQL default port
EXPOSE 5432

# TODO: Add local volume
# Volume for persistent data
VOLUME /var/lib/postgresql/data

# Set the default command to run when starting the container
CMD ["postgres"]
